#:schema node_modules/wrangler/config-schema.json
name = "with-hp-deployer"
main = "src/index.ts"
compatibility_date = "2024-05-24"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 0 * * *"] # Run at 00:00 every day
